using System;
using System.Collections.Generic;
using Optimizer.WinUI.Models;
using Xunit;

namespace Optimizer.WinUI.Tests;

/// <summary>
/// Tests for lightweight model classes that have computed properties or validation logic.
/// </summary>
public class ModelTests
{
    // ── ProcessBottleneck ────────────────────────────────────────────────

    [Theory]
    [InlineData("High", "#EF4444")]
    [InlineData("Medium", "#F59E0B")]
    [InlineData("Low", "#3B82F6")]
    [InlineData("Unknown", "#3B82F6")] // default path
    public void ProcessBottleneck_SeverityColor_MatchesExpected(string severity, string expectedColor)
    {
        var b = new ProcessBottleneck { Severity = severity };
        Assert.Equal(expectedColor, b.SeverityColor);
    }

    [Fact]
    public void ProcessBottleneck_DisplayValue_FormatsCorrectly()
    {
        var b = new ProcessBottleneck { Value = 512.5, ValueUnit = "MB" };
        // DisplayValue uses F1 formatting; just verify it contains the unit and non-empty value
        Assert.Contains("MB", b.DisplayValue, StringComparison.Ordinal);
        Assert.Contains("512", b.DisplayValue, StringComparison.Ordinal); // integer part always present
    }

    [Fact]
    public void BottleneckReport_StartsWithEmptyOffendersAndSummary()
    {
        var report = new BottleneckReport();
        Assert.Empty(report.TopOffenders);
        Assert.Equal("", report.Summary);
    }

    // ── SettingsProfile ──────────────────────────────────────────────────

    [Fact]
    public void SettingsProfile_IdIsAutoGenerated()
    {
        var p1 = new SettingsProfile();
        var p2 = new SettingsProfile();
        Assert.NotEqual(p1.Id, p2.Id);
        Assert.NotEmpty(p1.Id);
    }

    [Fact]
    public void SettingsProfile_DefaultProfileType_IsCustom()
    {
        var profile = new SettingsProfile();
        Assert.Equal(ProfileType.Custom, profile.ProfileType);
    }

    // ── HistoryEntry ──────────────────────────────────────────────────────

    [Fact]
    public void HistoryEntry_IdIsAutoGenerated()
    {
        var e1 = new HistoryEntry();
        var e2 = new HistoryEntry();
        Assert.NotEqual(e1.Id, e2.Id);
    }

    [Fact]
    public void HistoryEntry_DefaultAction_IsApplied()
    {
        var entry = new HistoryEntry();
        Assert.Equal(HistoryAction.Applied, entry.Action);
    }

    [Fact]
    public void HistoryEntry_IsUndone_DefaultsFalse()
    {
        var entry = new HistoryEntry();
        Assert.False(entry.IsUndone);
    }
}
