using System;
using System.Collections.Generic;
using Optimizer.WinUI.Models;
using Xunit;

namespace Optimizer.WinUI.Tests;

/// <summary>
/// Tests for lightweight model classes that have computed properties or validation logic.
/// </summary>
public class ModelTests
{
    // ── ProcessBottleneck ────────────────────────────────────────────────

    [Theory]
    [InlineData("High", "#EF4444")]
    [InlineData("Medium", "#F59E0B")]
    [InlineData("Low", "#3B82F6")]
    [InlineData("Unknown", "#3B82F6")] // default path
    public void ProcessBottleneck_SeverityColor_MatchesExpected(string severity, string expectedColor)
    {
        var b = new ProcessBottleneck { Severity = severity };
        Assert.Equal(expectedColor, b.SeverityColor);
    }

    [Fact]
    public void ProcessBottleneck_DisplayValue_FormatsCorrectly()
    {
        var b = new ProcessBottleneck { Value = 512.5, ValueUnit = "MB" };
        // DisplayValue uses F1 formatting; just verify it contains the unit and non-empty value
        Assert.Contains("MB", b.DisplayValue);
        Assert.Contains("512", b.DisplayValue); // integer part always present
    }

    [Fact]
    public void BottleneckReport_StartsWithEmptyOffendersAndSummary()
    {
        var report = new BottleneckReport();
        Assert.Empty(report.TopOffenders);
        Assert.Equal("", report.Summary);
    }

    // ── MarketplaceEntry ──────────────────────────────────────────────────

    [Theory]
    [InlineData(0, "0")]
    [InlineData(999, "999")]
    public void MarketplaceEntry_DownloadsText_SmallNumbers_NoSuffix(int downloads, string expected)
    {
        var entry = new MarketplaceEntry { Downloads = downloads };
        Assert.Equal(expected, entry.DownloadsText);
    }

    [Theory]
    [InlineData(1_001)]   // strictly > 1000, gets K suffix
    [InlineData(1_500)]
    [InlineData(5_000)]
    public void MarketplaceEntry_DownloadsText_Thousands_HasKSuffix(int downloads)
    {
        var entry = new MarketplaceEntry { Downloads = downloads };
        // Culture-agnostic: just verify "K" suffix present
        Assert.EndsWith("K", entry.DownloadsText);
    }

    [Theory]
    [InlineData(1_000_001)]  // strictly > 1_000_000, gets M suffix
    [InlineData(2_500_000)]
    public void MarketplaceEntry_DownloadsText_Millions_HasMSuffix(int downloads)
    {
        var entry = new MarketplaceEntry { Downloads = downloads };
        Assert.EndsWith("M", entry.DownloadsText);
    }

    [Fact]
    public void MarketplaceEntry_DownloadsText_ExactlyThousand_FormatsAsK()
    {
        // Boundary at >= 1_000 (inclusive) — exactly 1000 returns "1.0K"
        var entry = new MarketplaceEntry { Downloads = 1_000 };
        Assert.Equal("1.0K", entry.DownloadsText);
    }

    [Fact]
    public void MarketplaceEntry_DownloadsText_NineHundredNinetyNine_IsRawNumber()
    {
        var entry = new MarketplaceEntry { Downloads = 999 };
        Assert.Equal("999", entry.DownloadsText);
    }

    [Fact]
    public void MarketplaceEntry_RatingText_ContainsCountInParentheses()
    {
        var entry = new MarketplaceEntry { AverageRating = 4.5, RatingCount = 123 };
        // Culture-agnostic: verify rating contains the count
        Assert.Contains("(123)", entry.RatingText);
    }

    [Fact]
    public void MarketplaceEntry_TagsText_JoinedWithBullet()
    {
        var entry = new MarketplaceEntry
        {
            Tags = new List<string> { "Gaming", "Performance", "GPU" }
        };
        Assert.Equal("Gaming • Performance • GPU", entry.TagsText);
    }

    [Fact]
    public void MarketplaceEntry_EmptyTags_ReturnsEmptyString()
    {
        var entry = new MarketplaceEntry { Tags = new List<string>() };
        Assert.Equal("", entry.TagsText);
    }

    // ── SettingsProfile ──────────────────────────────────────────────────

    [Fact]
    public void SettingsProfile_IdIsAutoGenerated()
    {
        var p1 = new SettingsProfile();
        var p2 = new SettingsProfile();
        Assert.NotEqual(p1.Id, p2.Id);
        Assert.NotEmpty(p1.Id);
    }

    [Fact]
    public void SettingsProfile_DefaultProfileType_IsCustom()
    {
        var profile = new SettingsProfile();
        Assert.Equal(ProfileType.Custom, profile.ProfileType);
    }

    // ── HistoryEntry ──────────────────────────────────────────────────────

    [Fact]
    public void HistoryEntry_IdIsAutoGenerated()
    {
        var e1 = new HistoryEntry();
        var e2 = new HistoryEntry();
        Assert.NotEqual(e1.Id, e2.Id);
    }

    [Fact]
    public void HistoryEntry_DefaultAction_IsApplied()
    {
        var entry = new HistoryEntry();
        Assert.Equal(HistoryAction.Applied, entry.Action);
    }

    [Fact]
    public void HistoryEntry_IsUndone_DefaultsFalse()
    {
        var entry = new HistoryEntry();
        Assert.False(entry.IsUndone);
    }
}
