using System.Text;
using System.Text.Json;
using Optimizer.WinUI.Models;

namespace Optimizer.WinUI.Services;

public class TemplatesService : ITemplatesService
{
    private readonly string _storeFile = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "Optimizer", "config-templates.json");

    private List<ConfigTemplate> _templates = [];

    public TemplatesService() { Load(); }

    // ── Persistence ───────────────────────────────────────────────────────────

    private void Load()
    {
        try
        {
            if (File.Exists(_storeFile))
                _templates = JsonSerializer.Deserialize<List<ConfigTemplate>>(
                    File.ReadAllText(_storeFile)) ?? [];
        }
        catch { }
    }

    private void Save()
    {
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(_storeFile)!);
            File.WriteAllText(_storeFile,
                JsonSerializer.Serialize(_templates,
                    new JsonSerializerOptions { WriteIndented = true }));
        }
        catch { }
    }

    // ── ITemplatesService ─────────────────────────────────────────────────────

    public Task<IReadOnlyList<ConfigTemplate>> GetTemplatesAsync()
        => Task.FromResult<IReadOnlyList<ConfigTemplate>>(_templates);

    public Task<ConfigTemplate> CreateFromCurrentStateAsync(string name, string description)
    {
        var template = new ConfigTemplate
        {
            Id          = Guid.NewGuid().ToString(),
            Name        = name,
            Description = description,
            Format      = "DSC",
            CreatedAt   = DateTime.Now,
            RegistryChanges = new Dictionary<string, string>
            {
                // Common privacy / security registry tweaks captured as a snapshot
                [@"HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection|AllowTelemetry"] = "0",
                [@"HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo|Enabled"] = "0",
                [@"HKLM\SYSTEM\CurrentControlSet\Services\DiagTrack|Start"]                 = "4",
                [@"HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU|NoAutoUpdate"] = "0"
            }
        };
        _templates.Add(template);
        Save();
        return Task.FromResult(template);
    }

    public async Task<string> ExportToDscAsync(ConfigTemplate template)
    {
        var dir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
            "Optimizer Templates");
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, $"{Sanitize(template.Name)}-dsc.ps1");

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Optimizer — DSC Configuration");
        sb.AppendLine($"# Template : {template.Name}");
        sb.AppendLine($"# Created  : {template.CreatedAt:yyyy-MM-dd HH:mm}");
        sb.AppendLine();
        sb.AppendLine("Configuration OptimizerTemplate");
        sb.AppendLine("{");
        sb.AppendLine("    Import-DscResource -ModuleName PSDesiredStateConfiguration");
        sb.AppendLine("    Node 'localhost'");
        sb.AppendLine("    {");

        var index = 0;
        foreach (var (keyVal, data) in template.RegistryChanges)
        {
            var parts     = keyVal.Split('|');
            var regKey    = parts[0];
            var valueName = parts.Length > 1 ? parts[1] : "Value";
            var resourceId = $"RegSetting{++index}";

            sb.AppendLine($"        Registry {resourceId}");
            sb.AppendLine("        {");
            sb.AppendLine("            Ensure    = 'Present'");
            sb.AppendLine($"            Key       = '{regKey}'");
            sb.AppendLine($"            ValueName = '{valueName}'");
            sb.AppendLine($"            ValueData = '{data}'");
            sb.AppendLine("            ValueType = 'DWord'");
            sb.AppendLine("        }");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("OptimizerTemplate");
        sb.AppendLine("Start-DscConfiguration -Path .\\OptimizerTemplate -Wait -Verbose");

        await File.WriteAllTextAsync(path, sb.ToString());
        return path;
    }

    public async Task<string> ExportToIntuneAsync(ConfigTemplate template)
    {
        var dir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
            "Optimizer Templates");
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, $"{Sanitize(template.Name)}-intune.json");

        var omaSettings = new List<object>();
        foreach (var (keyVal, data) in template.RegistryChanges)
        {
            var parts     = keyVal.Split('|');
            var regKey    = parts[0];
            var valueName = parts.Length > 1 ? parts[1] : "Value";

            // Convert registry path to OMA-URI style
            var omaUri = $"./Vendor/MSFT/Registry/{regKey.Replace('\\', '/')}/{valueName}";
            omaSettings.Add(new
            {
                @odata_type = "#microsoft.graph.omaSettingInteger",
                displayName = $"{valueName} ({regKey.Split('\\').Last()})",
                omaUri,
                value       = int.TryParse(data, out var intVal) ? intVal : 0
            });
        }

        var profile = new
        {
            @odata_type = "#microsoft.graph.windows10CustomConfiguration",
            displayName = template.Name,
            description = template.Description,
            omaSettings
        };

        var json = JsonSerializer.Serialize(profile,
            new JsonSerializerOptions { WriteIndented = true, PropertyNamingPolicy = null });

        // Fix @odata.type (serializer changes _ to .)
        json = json.Replace("odata_type", "@odata.type");

        await File.WriteAllTextAsync(path, json);
        return path;
    }

    public async Task<string> ExportToWingetAsync(ConfigTemplate template)
    {
        var dir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
            "Optimizer Templates");
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, $"{Sanitize(template.Name)}-winget.yaml");

        var sb = new StringBuilder();
        sb.AppendLine("# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2");
        sb.AppendLine($"# Generated by Optimizer — {template.Name}");
        sb.AppendLine($"# Created: {template.CreatedAt:yyyy-MM-dd HH:mm}");
        sb.AppendLine("properties:");
        sb.AppendLine("  configurationVersion: 0.2.0");
        sb.AppendLine("  resources:");

        foreach (var (keyVal, data) in template.RegistryChanges)
        {
            var parts     = keyVal.Split('|');
            var regKey    = parts[0].Replace("HKLM\\", "HKLM:\\");
            var valueName = parts.Length > 1 ? parts[1] : "Value";

            sb.AppendLine("    - resource: PSDscResources/Registry");
            sb.AppendLine("      directives:");
            sb.AppendLine($"        description: Set {valueName}");
            sb.AppendLine("      settings:");
            sb.AppendLine("        Ensure: Present");
            sb.AppendLine($"        Key: {regKey}");
            sb.AppendLine($"        ValueName: {valueName}");
            sb.AppendLine($"        ValueData: '{data}'");
            sb.AppendLine("        ValueType: DWord");
        }

        await File.WriteAllTextAsync(path, sb.ToString());
        return path;
    }

    public Task DeleteAsync(string id)
    {
        _templates.RemoveAll(t => t.Id == id);
        Save();
        return Task.CompletedTask;
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string Sanitize(string name)
        => string.Concat(name.Select(c => Path.GetInvalidFileNameChars().Contains(c) ? '_' : c));
}
